### ISSUE TITLE
[BUG] "Change Wake Word" Error Handling

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon_speech#135]
### Description

"Change WW" requests that fail can result in 2 active WW when the user requests a change. On the module side.

### Steps to Reproduce

- Update a released image to 23.3.15
- Ask "change my wake word to hey mycroft"
- If skill responds with an error, check that the new WW is not enabled in settings

### Relevant Code

https://github.com/NeonGeckoCom/neon_speech/blob/66675419c2c9925ae11b143bd2f0a415916af9aa/neon_speech/service.py#L213-L220

### Other Notes

This can probably just put the changes in a try/except that restores the original config in the exception case

**Comment by NeonDaniel** [comment]
Mar 17 12:41:11 neon neon-speech.py[3719]: 2023-03-17 12:41:11.255 - voice - neon_speech.service:handle_enable_wake_word:209 - INFO - Enabling wake word: hey_mycroft
Mar 17 12:41:11 neon neon-speech.py[3719]: exception calling callback for <Future at 0x7f30178b90 state=finished raised FileNotFoundError>
Mar 17 12:41:11 neon neon-speech.py[3719]: Traceback (most recent call last):
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
Mar 17 12:41:11 neon neon-speech.py[3719]:     callback(self)
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/pyee/_executor.py", line 56, in _callback
Mar 17 12:41:11 neon neon-speech.py[3719]:     self.emit('error', exc)
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/pyee/_base.py", line 116, in emit
Mar 17 12:41:11 neon neon-speech.py[3719]:     self._emit_handle_potential_error(event, args[0] if args else None)
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
Mar 17 12:41:11 neon neon-speech.py[3719]:     raise error
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Mar 17 12:41:11 neon neon-speech.py[3719]:     result = self.fn(*self.args, **self.kwargs)
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/neon_speech/service.py", line 213, in handle_enable_wake_word
Mar 17 12:41:11 neon neon-speech.py[3719]:     update_mycroft_config(config_patch)
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/ovos_config/config.py", line 377, in update_mycroft_config
Mar 17 12:41:11 neon neon-speech.py[3719]:     conf = MycroftUserConfig()
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/ovos_config/models.py", line 199, in __init__
Mar 17 12:41:11 neon neon-speech.py[3719]:     super().__init__(USER_CONFIG)
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/ovos_config/models.py", line 56, in __init__
Mar 17 12:41:11 neon neon-speech.py[3719]:     self.load_local(path)
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/ovos_config/models.py", line 86, in load_local
Mar 17 12:41:11 neon neon-speech.py[3719]:     with self.__lock:
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/combo_lock/combo_lock.py", line 75, in __enter__
Mar 17 12:41:11 neon neon-speech.py[3719]:     self.acquire()
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/combo_lock/combo_lock.py", line 65, in acquire
Mar 17 12:41:11 neon neon-speech.py[3719]:     self.plock.acquire()
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/filelock/_api.py", line 173, in acquire
Mar 17 12:41:11 neon neon-speech.py[3719]:     self._acquire()
Mar 17 12:41:11 neon neon-speech.py[3719]:   File "/home/neon/venv/lib/python3.7/site-packages/filelock/_unix.py", line 35, in _acquire
Mar 17 12:41:11 neon neon-speech.py[3719]:     fd = os.open(self._lock_file, open_mode)
Mar 17 12:41:11 neon neon-speech.py[3719]: FileNotFoundError: [Errno 2] No such file or directory: '/run/shm/combo_locks/b3Zvc19jb25maWc=.lock'
